name: proxy_app
description: A proxy application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"  # Dart SDK的版本
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.2
  http: ^1.1.0 
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # Windows特性
  win32: ^5.1.1
  # win32_registry: ^1.1.2
  ffi: ^2.1.0
  
  # 窗口管理
  window_manager: ^0.3.7
  
  # 路径处理
  path: ^1.8.3
  
  # URL启动
  url_launcher: ^6.2.2
  
  # 图标
  cupertino_icons: ^1.0.6
  
  # 新增：设备信息获取
  device_info_plus: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # 应用图标和资源
  assets:
    - assets/images/
    - assets/js/
    - assets/geoip.dat
    - assets/geoip-only-cn-private.dat
    - assets/geosite.dat
  
  # 字体配置（如果需要）
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
