name: Build Windows Release

on:
  # 仅保留手动触发方式
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: false
        default: '1.0.0'
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows app
      run: flutter build windows --release
    
    - name: Copy V2Ray core and CloudflareST from project
      shell: pwsh
      run: |
        # 从项目目录复制V2Ray核心文件和CloudflareST工具
        $sourcePath = "windows\runner\v2ray"
        $buildPath = "build\windows\x64\runner\Release\v2ray"
        
        # 创建目标目录
        New-Item -ItemType Directory -Force -Path $buildPath
        
        # 复制V2Ray核心文件
        if (Test-Path "$sourcePath\v2ray.exe") {
            Copy-Item "$sourcePath\v2ray.exe" -Destination "$buildPath\" -Force
            Write-Host "✓ Copied v2ray.exe"
        } else {
            Write-Error "v2ray.exe not found in $sourcePath"
            exit 1
        }
        
        if (Test-Path "$sourcePath\geoip.dat") {
            Copy-Item "$sourcePath\geoip.dat" -Destination "$buildPath\" -Force
            Write-Host "✓ Copied geoip.dat"
        } else {
            Write-Error "geoip.dat not found in $sourcePath"
            exit 1
        }
        
        if (Test-Path "$sourcePath\geosite.dat") {
            Copy-Item "$sourcePath\geosite.dat" -Destination "$buildPath\" -Force
            Write-Host "✓ Copied geosite.dat"
        } else {
            Write-Error "geosite.dat not found in $sourcePath"
            exit 1
        }
        
        Write-Host "V2Ray core files copied successfully"
        
        # 复制CloudflareST工具到构建目录根目录
        $sourcePathCF = "windows\runner"
        $buildPathRoot = "build\windows\x64\runner\Release"
        
        if (Test-Path "$sourcePathCF\cftest.exe") {
            Copy-Item "$sourcePathCF\cftest.exe" -Destination "$buildPathRoot\" -Force
            Write-Host "✓ Copied cftest.exe"
        } else {
            Write-Error "cftest.exe not found in $sourcePathCF"
            exit 1
        }
        
        if (Test-Path "$sourcePathCF\ip.txt") {
            Copy-Item "$sourcePathCF\ip.txt" -Destination "$buildPathRoot\" -Force
            Write-Host "✓ Copied ip.txt"
        } else {
            Write-Error "ip.txt not found in $sourcePathCF"
            exit 1
        }
        
        Write-Host "CloudflareST files copied successfully"
    
    - name: Package application
      shell: pwsh
      run: |
        # 获取版本号 - 优先使用手动输入的版本，否则使用分支名或标签名
        $version = "${{ github.event.inputs.version }}"
        if ([string]::IsNullOrEmpty($version)) {
            $version = "${{ github.ref_name }}".TrimStart("v")
        }
        
        $buildPath = "build\windows\x64\runner\Release"
        $outputName = "CFVPN-Windows-x64-$version"
        
        # 创建发布目录
        New-Item -ItemType Directory -Force -Path "release"
        
        # 压缩所有文件
        Compress-Archive -Path "$buildPath\*" -DestinationPath "release\$outputName.zip"
        
        Write-Host "Package created: $outputName.zip"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: release/*.zip
    
    - name: Create Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
