name: Download libv2ray.aar
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'libv2ray version (e.g., v25.8.3)'
        required: true
        default: 'v25.8.3'
        type: string
jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions.checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download libv2ray.aar
      run: |
        # 创建 libs 目录
        mkdir -p android/app/libs
        
        # 下载 libv2ray.aar
        echo "Downloading libv2ray.aar version ${{ github.event.inputs.version }}..."
        wget -O android/app/libs/libv2ray.aar \
          https://github.com/2dust/AndroidLibXrayLite/releases/download/${{ github.event.inputs.version }}/libv2ray.aar
        
        # 验证下载
        if [ ! -f android/app/libs/libv2ray.aar ]; then
          echo "Error: Failed to download libv2ray.aar"
          exit 1
        fi
        
        # 显示文件信息
        echo "Downloaded successfully!"
        ls -lh android/app/libs/libv2ray.aar
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # 添加文件到 git
        git add android/app/libs/libv2ray.aar
        
        # 检查是否有更改
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update libv2ray.aar to ${{ github.event.inputs.version }}"
          git push
          echo "File committed and pushed successfully!"
        fi
